# Generated by Django 3.0.3 on 2020-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='school',
            field=models.CharField(default='ERICA', max_length=30),
        ),
    ]
